/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    //For this assignment you will be building a bitmap (.bmp) transformer CLI
    //It will read a bitmap in from disk
    //run one or more color or raster transforms
    //and then write it out to a new file.
    //This project will require manipulating binary data
    //Your solution should be composed of small tested methods that solve specific problems
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
