/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap;

import org.junit.Test;

import java.awt.image.BufferedImage;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    BitMap testThis = new BitMap();
    @Test public void test_getBmpImage(){
        BufferedImage image= testThis.getBmpImage("src/main/resources/coffee.bmp");
        assertNotNull("Bitmap image should not be null", image);
        assertEquals("Should have a hight property", image.getHeight(),250);
        assertEquals("Should have a width property", image.getWidth(),640);
    }
    @Test public void test_getDementions(){
        BufferedImage image= testThis.getBmpImage("src/main/resources/coffee.bmp");
        int[]dementions=testThis.getDementions(image);
        assertEquals("returns the correct height demention", dementions[0],250);
        assertEquals("returns the correct width demention", dementions[1], 640);

    }

}
